apiVersion: apps/v1
kind: Deployment
metadata:
  name: parusov-ikbo-30-21
  labels:
    app: parusov-ikbo-30-21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parusov-ikbo-30-21
  template:
    metadata:
      labels:
        app: parusov-ikbo-30-21
    spec:
      containers:
        - name: parusov-ikbo-30-21
          image: truecmetanka/node-server
          ports: 
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: parusov-ikbo-30-21-service
spec:
  selector:
    app: parusov-ikbo-30-21
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
