apiVersion: apps/v1
kind: Deployment
metadata:
  name: muhametshin-ikbo-20-21
  labels:
    app: muhametshin-ikbo-20-21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muhametshin-ikbo-20-21
  template:
    metadata:
      labels:
        app: muhametshin-ikbo-20-21
    spec:
      containers:
        - name: muhametshin-ikbo-20-21
          image: muhametshin/node-server
          ports: 
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: muhametshin-ikbo-20-21-service
spec:
  selector:
    app: muhametshin-ikbo-20-21
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
