services:
  gateway:
    container_name: gateway
    build:
      context: gateway/
      dockerfile: Dockerfile
    ports:
      - "80:8083"
    volumes:
      - ./gateway/web/index.html:/app/index.html
      - ./gateway/web/script.js:/app/script.js

  task-service:
    container_name: task_service
    build:
      context: task_service/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - task_postgres

  task_postgres:
    container_name: task_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task
    ports:
      - "5435:5432"

  notification-service:
    container_name: notification-service
    build:
      context: notification_service/
      dockerfile: Dockerfile
    depends_on:
      - notification_postgres
    ports:
      - "8081:8081"

  notification_postgres:
    container_name: notification_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification
    ports:
      - "5433:5432"

  user-service:
    container_name: user-service
    build:
      context: user_service/
      dockerfile: Dockerfile
    depends_on:
      - user_postgres
    ports:
      - "8082:8082"


  user_postgres:
    container_name: user_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5434:5432"

